### PR TITLE
Workspace one

### PR DESCRIPTION
**Pull request by kylesmartin**
I added a backend for Workspace One along with RTR functionality.

### CODE REVIEW

**Review by isimluk — APPROVED** [review]
Looks good to me.

**Comment by isimluk** [comment]
Some of the CI/CD failures may uncover real issues worth fixing. But feel free to relax the checkers if you feel compelled to. pylint and flake8 may be configured though https://github.com/CrowdStrike/falcon-integration-gateway/blob/main/setup.cfg 

Good looks good. Haven't tested though.

**Comment by kylesmartin** [comment]
Fixed all linting errors, should be good to merge now.

**Review by isimluk — APPROVED** [review]
Thanks!

**Pull request merged**
