### PR TITLE
Provide LICENSE file

### PR DESCRIPTION
**Pull request by isimluk**
While we have already mentioned license in setup.py, we never provided license
text in the repo.

### CODE REVIEW

**Comment by redhatrises** [comment]
Opps. Ack.

**Comment by shawndwells** [comment]
Can the license content from the python file be deleted?

**Comment by redhatrises** [comment]
> Can the license content from the python file be deleted?

What are you thinking around this? Duplicate instances of license? or...?

**Comment by shawndwells** [comment]
> > Can the license content from the python file be deleted?
> 
> What are you thinking around this? Duplicate instances of license? or...?

My mistake. Interpreted @isimluk's comment as meaning the full license text was in the python file. In looking at the file, I now understand he was referring to https://github.com/CrowdStrike/falcon-integration-gateway/blob/main/setup.py#L49

We're good!

**Comment by isimluk** [comment]
Indeed, we are very good!

Thanks.

**Pull request merged**
