### PR TITLE
update VMware name in README

### PR DESCRIPTION
**Pull request by shawndwells**
WORKSPACEONE -> Workspace ONE

aligns with vmware's naming scheme/capitalization

### CODE REVIEW

**Comment by shawndwells** [comment]
@isimluk wasn't sure if things should be called `WORKSPACEONE` or `Workspace ONE`. Opened a PR to check/start the conversation.

**Comment by redhatrises** [comment]
> @isimluk wasn't sure if things should be called `WORKSPACEONE` or `Workspace ONE`. Opened a PR to check/start the conversation.

I believe that `WORKSPACEONE` is the option to put into the configuration file.

**Comment by shawndwells** [comment]
> > @isimluk wasn't sure if things should be called `WORKSPACEONE` or `Workspace ONE`. Opened a PR to check/start the conversation.
> 
> I believe that `WORKSPACEONE` is the option to put into the configuration file.

This is the human readable name in the README

**Comment by redhatrises** [comment]
> > > @isimluk wasn't sure if things should be called `WORKSPACEONE` or `Workspace ONE`. Opened a PR to check/start the conversation.
> > 
> > 
> > I believe that `WORKSPACEONE` is the option to put into the configuration file.
> 
> This is the human readable name in the README

You are right! derp

**Review by isimluk — APPROVED** [review]
:+1: while the `WORKSPACEONE` is the name of the backend it really looks ugly in the main readme.

**Pull request merged**
